name: Platformer Generated fghfghfg Build
'on':
  push:
    tags:
      - ''
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: us.gcr.io/testtt/course-era-test-1
      CONTAINER_REGISTRY: https://us.gcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Setup GCloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY_2377CB50_D095_4FD3_900E_F15902CC1EEB }}
          project_id: ${{ secrets.PROJECT_ID_2377CB50_D095_4FD3_900E_F15902CC1EEB }}
          export_default_credentials: true
      - name: Use GCloud CLI
        run: gcloud auth configure-docker -q
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --file Dockerfile .
      - name: GCR Image Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_BC93C40C_65F2_4E8A_AB5C_6401D70DC4A1}}
          project-id: ${{secrets.PROJECT_ID_BC93C40C_65F2_4E8A_AB5C_6401D70DC4A1}}
          token: ${{secrets.AUTOGENERATED_CICD_BC93C40C_65F2_4E8A_AB5C_6401D70DC4A1}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: 24a9a296-6015-4c17-b435-c6dd2b754d56
