name: Platformer Generated sameeratest Build
'on':
  push:
    tags:
      - test
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: hub.docker.com/course-era-test-1
      CONTAINER_REGISTRY: hub.docker.com
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME_68213672_5E54_4B93_9072_13A4BF783269 }}
          password: ${{ secrets.DOCKER_PASSWORD_68213672_5E54_4B93_9072_13A4BF783269 }}
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --file Dockerfile .
      - name: Docker Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_BC93C40C_65F2_4E8A_AB5C_6401D70DC4A1}}
          project-id: ${{secrets.PROJECT_ID_BC93C40C_65F2_4E8A_AB5C_6401D70DC4A1}}
          token: ${{secrets.AUTOGENERATED_CICD_BC93C40C_65F2_4E8A_AB5C_6401D70DC4A1}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: a6c49b1c-cdeb-4e9d-8d13-dc895ef17ca8
