name: Platformer Generated sameeratest7 Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: hub.docker.com/course-era-test-1
      CONTAINER_REGISTRY: hub.docker.com
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output
          name=SOURCE_TAG::${GITHUB_REF#refs/heads/}-${{github.sha}}
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME_E4FCA29D_754F_4988_8204_07B5A31C4803 }}
          password: ${{ secrets.DOCKER_PASSWORD_E4FCA29D_754F_4988_8204_07B5A31C4803 }}
      - name: Build the Docker image
        run: docker build --tag
          ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --file
          Dockerfile .
      - name: Docker Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_EA07C436_736A_4585_A8E5_DA7865D9C6F0}}
          project-id: ${{secrets.PROJECT_ID_EA07C436_736A_4585_A8E5_DA7865D9C6F0}}
          token: ${{secrets.AUTOGENERATED_CICD_EA07C436_736A_4585_A8E5_DA7865D9C6F0}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: f5cae4e3-5944-4c19-a57e-db5990b0084c
