name: Platformer Generated sameeratest Build
'on':
  push:
    tags:
      - ''
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: gcr.io/platformer-november/course-era-test-1
      CONTAINER_REGISTRY: https://gcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Setup GCloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY_1AA9958E_7967_484E_A33A_E778A01406DF }}
          project_id: ${{ secrets.PROJECT_ID_1AA9958E_7967_484E_A33A_E778A01406DF }}
          export_default_credentials: true
      - name: Use GCloud CLI
        run: gcloud auth configure-docker -q
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --file Dockerfile .
      - name: GCR Image Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_C67A833E_FA8B_4D68_94DD_E69A909C7FF0}}
          project-id: ${{secrets.PROJECT_ID_C67A833E_FA8B_4D68_94DD_E69A909C7FF0}}
          token: ${{secrets.AUTOGENERATED_CICD_C67A833E_FA8B_4D68_94DD_E69A909C7FF0}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: 7a961bb1-4b72-4eab-85cc-897f5ec72312
